### ISSUE TITLE
What is the expected longevity of this project

### ISSUE THREAD

**Issue by adriatic** [uhray/crud-mongoose#1]
My top focus is to build a serious **app** using MEAN stack (note the focus on app) so I have to rely a lot on the quality and stability of all npm fetched packages. crud-mongoose being one of them, In other words, I am not necessarily enjoying to keep writing Express router code that "converses" with the Angular front end, so your package seems like a good solution.

In particular, I am interested in solid handling of the "create if it does not exist, or add" combined with "update" mongoose API. At the moment I have the following rule

```
   // Create a new league
    app.post('/leagues', function(req, res) {
        League.create(req.body, function (err, league){
            if (err) 
                res.send(err);
            res.json(league);
        })
    })
```

Can you show me how to merge (or write separately) the create, add and update rules using crud-mongoose, please?

**Comment by rthomps7** [comment]
@adriatic the project has no end in site. We use it to build all our REST APIs.

The Readme should outline exactly what you're trying to do. Give it a read. You may want to read the Readme of CRUD (https://github.com/uhray/crud) first to help your understanding.
