### ISSUE TITLE
Add in 'allowDiskUse' to findAggregation workflow (potentially via an optional field)

### ISSUE THREAD

**Issue by nschappl** [uhray/crud-mongoose#2]
Bobby - just creating this GH issue as a placeholder for us to address in the future. Stats stopped returning for the CDLLife Job Board and Live Trucking recently due to the there being too much data for the database to do a sort with default options. 

Here is what mongo returned: https://trello-attachments.s3.amazonaws.com/58a387fd7aa639255067dc3e/5c8146c75701ee27d7af0f14/221280376a024db6c4ec9f32e78b1870/Screen_Shot_2019-03-13_at_4.14.23_PM.png

I got around this by switching out the `cm.findAggregation` call for a raw mongoose call that with the`allowDiskUse` option from here: https://mongoosejs.com/docs/4.x/docs/api.html#aggregate_Aggregate-allowDiskUse

Quick fix would be to just add this option by default to the call in `findAggregation()` so that this works by default with larger data aggregations that involve something intensive like a DB sort:

```
Model.aggregate(pipeline)
      .allowDiskUse(true)
      .exec((e, d) => {
        cb(e, d);
      });
```

Alternatively, we could make it a configureable option. At any rate, I didn't want to mess with crud-mongoose and deploy to npm without more discussion, so leaving this here for now.

**Comment by rthomps7** [comment]
#3
